apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerroyalepayment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burgerroyalepayment
    spec:
      containers:
        - name: burgerroyalepayment
          image: ${IMAGE_URI}
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: AWS__AccessKey
              value: ${ACCESS_KEY}
            - name: AWS__SecretKey
              value: ${SECRET_KEY}
            - name: AWS__SessionToken
              value: ${SESSION_TOKEN}
            - name: AWS__Region
              value: ${REGION}
            - name: MongoDB__ConnectionURI
              value: mongodb+srv://${PAYMENT_DB_USER}:${PAYMENT_DB_PASSWORD}@${PAYMENT_DB_CLUSTER_ADDRESS}/?retryWrites=true&w=majority&appName=${PAYMENT_DB_CLUSTER_NAME}
            - name: Jwt__Issuer
              value: ${JWT_ISSUER}
            - name: Jwt__Audience
              value: ${JWT_AUDIENCE}
            - name: Jwt__SecretKey
              value: ${JWT_SECRETKEY}

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
  selector:
    matchLabels:
      app: burgerroyalepayment