apiVersion: v1
kind: Service
metadata:
  name: burgerroyalepayment
spec:
  type: LoadBalancer
  selector:
    app: burgerroyalepayment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000