name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main", "develop"]
  
env:
  EKS_CLUSTER_NAME: burgerroyalepayment-cluster-eks
  ECR_REPOSITORY: burgerroyalepayment-ecr
  AWS_REGION: us-east-1

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
   
  tests:
   name: Unit Tests
   runs-on: ubuntu-latest
   needs: Build
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Domain Tests
      run: |
        cd tests
        cd BurgerRoyale.Payment.Domain.Tests
        dotnet test
      
    - name: Application Tests
      run: |
        cd tests
        cd BurgerRoyale.Payment.Application.Tests
        dotnet test

  integrationTests:
   name: Integration Tests
   runs-on: ubuntu-latest
   needs: tests
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: App Settings Variable Substitution
      env:
        ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        REGION: ${{ env.AWS_REGION }}
        PAYMENT_DB_USER: ${{ secrets.PAYMENT_DB_USER }}
        PAYMENT_DB_PASSWORD: ${{ secrets.PAYMENT_DB_PASSWORD }}
        PAYMENT_DB_CLUSTER_ADDRESS: ${{ secrets.PAYMENT_DB_CLUSTER_ADDRESS }}
        PAYMENT_DB_CLUSTER_NAME: ${{ secrets.PAYMENT_DB_CLUSTER_NAME }}
      run: |
        cd src
        cd BurgerRoyale.Payment.API
        sed -i 's|${ACCESS_KEY}|'"$ACCESS_KEY"'|g' appsettings.json
        sed -i 's|${SECRET_KEY}|'"$SECRET_KEY"'|g' appsettings.json
        sed -i 's|${SESSION_TOKEN}|'"$SESSION_TOKEN"'|g' appsettings.json
        sed -i 's|${REGION}|'"$REGION"'|g' appsettings.json
        
        sed -i 's|${PAYMENT_DB_USER}|'"$PAYMENT_DB_USER"'|g' appsettings.json
        sed -i 's|${PAYMENT_DB_PASSWORD}|'"$PAYMENT_DB_PASSWORD"'|g' appsettings.json
        sed -i 's|${PAYMENT_DB_CLUSTER_ADDRESS}|'"$PAYMENT_DB_CLUSTER_ADDRESS"'|g' appsettings.json
        sed -i 's|${PAYMENT_DB_CLUSTER_NAME}|'"$PAYMENT_DB_CLUSTER_NAME"'|g' appsettings.json
        cat appsettings.json
      
    - name: Behavior Tests
      run: |
        cd tests
        cd BurgerRoyale.Payment.BehaviorTests
        dotnet test
        
  publishImage:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: integrationTests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deployToEKs:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: publishImage

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Replace variables in Kubernetes manifest
      env:
        IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
    
        CONNECTON_URI: ${{ secrets.PAYMENT_CONNECTION_URI }}
        
        JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
        JWT_SECRETKEY: ${{ secrets.JWT_SECRET_KEY }}
      run: |
        cd Kubernetes
        sed -i 's|${IMAGE_URI}|'"$IMAGE_URI"'|g' api-deployment.yaml
        
        sed -i 's|${CONNECTION_URI}|'"$CONNECTON_URI"'|g' api-deployment.yaml

        sed -i 's|${JWT_ISSUER}|'"$JWT_ISSUER"'|g' api-deployment.yaml
        sed -i 's|${JWT_AUDIENCE}|'"$JWT_AUDIENCE"'|g' api-deployment.yaml
        sed -i 's|${JWT_SECRETKEY}|'"$JWT_SECRETKEY"'|g' api-deployment.yaml

    - name: Deploy to EKS
      run: |
        cd Kubernetes
        kubectl apply -f api-deployment.yaml
        kubectl apply -f api-svc.yaml
        
        kubectl apply -f api-scaleobject.yaml
